# Generated by Django 3.0.3 on 2022-09-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=100)),
                ('_submitter', models.CharField(max_length=100)),
                ('_species', models.CharField(max_length=30)),
                ('_breed', models.CharField(blank=True, max_length=30)),
                ('_description', models.TextField()),
                ('_sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField()),
                ('_submissionDate', models.DateTimeField()),
                ('_vaccinations', models.ManyToManyField(blank=True, to='firstApp.Vaccine')),
            ],
        ),
    ]
