# Generated by Django 3.0.3 on 2022-09-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='age',
            new_name='age',
        ),
    ]
