# Generated by Django 3.0.3 on 2022-09-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.BooleanField(verbose_name='Yes')),
                ('_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=100)),
                ('No', models.BooleanField(verbose_name='Yes')),
                ('_positions', models.ManyToManyField(blank=True, to='classes.Position')),
            ],
        ),
    ]
