# Generated by Django 3.0.3 on 2022-09-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='No',
        ),
        migrations.RemoveField(
            model_name='position',
            name='No',
        ),
        migrations.AddField(
            model_name='player',
            name='_specialist',
            field=models.BooleanField(default=False, verbose_name='Specialist'),
        ),
        migrations.AddField(
            model_name='position',
            name='_specialistPosition',
            field=models.BooleanField(default=False, verbose_name='Specialist Postion'),
        ),
    ]
